version: '3'
services:
  kas-test:
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: "redis"
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:v2.3.2
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:5.2.3
    volumes:
      - ./grafana/grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  hystrix-dashboard:
    image: mlabouardy/hystrix-dashboard:latest
    ports:
    - "9002:9002"

