spring:
  application:
    name: kas-test
  jackson:
    default-property-inclusion: NON_NULL

swagger:
  enabled: true

kas-test:
  packages:
    rest:
      baseUrl: http://opendata-ajuntament.barcelona.cat/
    service:
      defaultLimit: 10
    api:
      defaultLang: ca


